# Exercise 3:
***

## 1. Find the mean for row, column and all 

In [25]:
import numpy as np

m = np.arange(12).reshape((3, 4))
print(m)
print('column means {}'.format(np.mean(m, 0)))
print('row means {}'.format(np.mean(m, 1)))
print('all mean {}'.format(np.mean(m)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
column means [4. 5. 6. 7.]
row means [1.5 5.5 9.5]
all mean 5.5


## 2. product of two vectors

In [49]:
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])

print(np.outer(u,v),'\n')
print(np.array([[i * j for i in v] for j in u]), '\n')
print(u.reshape(4, 1)*v)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


## 3. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

In [96]:
x = np.random.uniform(0, 1, (10, 6))
print(x)
print(np.any(x))

[[0.96730227 0.82798877 0.6559455  0.61905554 0.47500313 0.42341601]
 [0.36974502 0.39227908 0.51233255 0.3503884  0.19905078 0.61159623]
 [0.25502682 0.96496408 0.45458737 0.0213886  0.60288857 0.94105056]
 [0.32640492 0.32748302 0.82360542 0.687699   0.34067508 0.66980159]
 [0.33468081 0.33669556 0.72034966 0.11975334 0.83225303 0.058514  ]
 [0.95785125 0.804295   0.26312142 0.73283158 0.23378724 0.39037812]
 [0.40794575 0.50435717 0.25849405 0.94044781 0.7706023  0.26549794]
 [0.05603527 0.43138746 0.01278542 0.66112283 0.12624372 0.26570743]
 [0.55581561 0.88238261 0.92174853 0.06540542 0.14755314 0.52520853]
 [0.32739752 0.62856953 0.14353037 0.14899539 0.59728957 0.4652224 ]]
True


## 4. Use np.linspace to create an array of 100 numbers between 0 and 2π (includsive).


In [126]:
from math import pi, sin, cos
import matplotlib.pyplot as plt
w = np.linspace(0, 2*pi, 100)
print(w, '\n')
print(w[::9], '\n')
print(w[::-1], '\n')

def sin_cos(x):
    return abs(sin(x)-cos(x)) < 0.1

w_out = list((filter(sin_cos, w)))
print(w_out)

%matplotlib inline
x = np.arange(0,4*np.pi,0.1)
y = np.sin(x)
z = np.cos(x)
plt.plot(x, y)
plt.plot(x, z)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'