# Exercise 4
***

## 1. create list and save as txt

In [16]:
import numpy as np

l = np.random.randint(0, 10, 100)
m = np.random.randint(0, 10, (5,5))
a_file = open("simple_data.txt", "w")
a_file = open("data.txt", "w")
np.savetxt("simple_data.txt", l)
np.savetxt("data.txt", m)

In [18]:
import csv

s = np.loadtxt("data.txt")
print(s)

[[4. 5. 5. 1. 7.]
 [6. 6. 7. 7. 0.]
 [8. 4. 3. 9. 9.]
 [8. 3. 1. 6. 4.]
 [6. 7. 6. 6. 4.]]
